### ISSUE TITLE
Hacktoberfest:  Make it easier to install

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/wifi-manager#2]
# Hacktoberfest:  Make it easier to install

Currently, there's no `Makefile` and way to installation the `macOS-wifi-cli` easily. As such, we need to provide users the ability to easily install the CLI with one-line command. For example:

```
# This should install the the CLI globally in system path
$ make install

# Uninstall
$ make uninstall
```

#### References: 
- https://github.com/tuladhar/set-brightness/blob/main/Makefile
- https://github.com/tuladhar/check_bandwidth/pull/5

- - -
Stay Safe & Happy Hacking,
Puru

**Comment by liisberg** [comment]
I would like to help with this, will you assign it to me?

**Comment by tuladhar** [comment]
Great, thanks @liisberg. I've assigned it to you.
