### ISSUE TITLE
'wifi-cli/' exists but is not an executable file.

### ISSUE THREAD

**Issue by sheldonrrr** [tuladhar/wifi-manager#4]
Hey Tuladhar,

I followed the steps:
`git clone https://github.com/tuladhar/wifi-cli`
`cd wifi-cli`
`make install`
But there is title remind.

1. Maybe because of the depency and I install depencies needed. But it exist.
2. Maybe because of the authority problem, after 
`chmod +x wifi-cli`
the authority is root, and it exist.

I install wifi-cli in another Mac successfully, but not in this work one. Same Intel Core.

This is interesting. Do you know this problem?

**Comment by tuladhar** [comment]
Thanks @sheldonrrr for raising an issue. That's interesting, I haven't encountered that issue myself, but happy to help debug. Do you mind sharing the screenshot or terminal output?

**Comment by sheldonrrr** [comment]
@tuladhar Of course. Here they are.
![截屏2023-02-01 下午6 18 34](https://user-images.githubusercontent.com/2425392/216015857-dca75cb3-15b3-4ea4-bb30-54156d328eab.png)

**Comment by sheldonrrr** [comment]
![截屏2023-02-01 下午6 19 36](https://user-images.githubusercontent.com/2425392/216016074-76dfd29b-bb00-40f2-8626-a384e08a0859.png)

**Comment by tuladhar** [comment]
Okay, I think I know whats wrong with your installation.

Try this.
```
$ rm -rf /usr/local/bin/wifi-cli
$ cd /tmp
$ git clone https://github.com/tuladhar/wifi-cli 
$ cd wifi-cli
$ sudo make install
```

**Comment by sheldonrrr** [comment]
![截屏2023-02-02 上午10 09 35](https://user-images.githubusercontent.com/2425392/216213771-fc21899c-cacf-4c80-9d41-e2d75e5fadca.png)

With your tips try again, but failed.
Your tips's goal is removing the cache?

**Comment by sheldonrrr** [comment]
Maybe because of the dependency python is python2? So I need to change python3 to python2 with pyenv tool?

**Comment by tuladhar** [comment]
> Maybe because of the dependency python is python2? So I need to change python3 to python2 with pyenv tool?

Yes, that's likely the problem. What do you see when you run this:
```
$ which python
$ env python
```

**Comment by sheldonrrr** [comment]
![截屏2023-02-02 下午6 02 59](https://user-images.githubusercontent.com/2425392/216294270-1a27741d-d26a-4b36-809e-dda6e7673104.png)

Thanks a lot,Tuladhar, I think this is the reason.
I will find the way. Sorry to have taken up your time.
